# fly.toml app configuration file generated for telegram-test-bot on 2023-04-24T18:25:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-test-bot"
primary_region = "ams"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  max_conns = 1000
  min_conns = 1
  processes = ["web"]

[[services]]
  internal_port = 9090
  protocol = "tcp"
  max_conns = 1000
  min_conns = 1
  processes = ["worker"]
[processes]
  web = "command to start web process"
  worker = "command to start worker process"